# See https://github.com/samueleaton/sentry/blob/master/.sentry.example.yml
# for more information about configuration options.

# By default, this file configures sentry to run the native specs for Myst
# every time any of the source files changes.
display_name: log2sqlite
info: true
# `|| echo` makes sure that sentry keeps running even if there the specs fail.
build: crystal build ./src/log2sqlite.cr
run: ./bin/test.sh
watch:
  - ./src/**/*.cr
  - ./lib/**/*.cr